### PR TITLE
Fix chart not showing in notebook in Visual Studio Code

### PR DESCRIPTION
**Pull request by olehmisar**
Looks like vscode does not allow multiple statements inside `<script>` tag. I fixed it by wrapping the whole code inside the already existing IIFE.

### CODE REVIEW

**Comment by wolframarnold** [comment]
I'm able to verify this patch in a Jupyter notebook running inside VSCode. Thanks for submitting this. @TechfaneTechnologies please consider merging this.

@olehmisar how did you debug this? For some reason I don't get any error messages or any type of output in the notebook.

**Comment by olehmisar** [comment]
@wolframarnold I did not get any errors too. Then, I printed raw html and started copy pasting it line by line to see when it stops working. It stopped working when I pasted two statements at the root of `<script>` tag

**Comment by ShabbirHasan1** [comment]
> I'm able to verify this patch in a Jupyter notebook running inside VSCode. Thanks for submitting this. @TechfaneTechnologies please consider merging this.
> 
> @olehmisar how did you debug this? For some reason I don't get any error messages or any type of output in the notebook.

Will Be Done. Thanks for verifying the patch. 🙏

**Comment by ShabbirHasan1** [comment]
> @wolframarnold I did not get any errors too. Then, I printed raw html and started copy pasting it line by line to see when it stops working. It stopped working when I pasted two statements at the root of `<script>` tag

Thanks for the pull request submission 🙏

**Pull request merged**
